export const ID = {
  CREW_TAB: 'crew-tab',
  TEAM_TAB: 'team-tab',
  FRONT_RADIO: 'frontend-course',
  BACKEND_RADIO: 'backend-course',
  CREW_NAME_INPUT: 'crew-name-input',
  ADD_CREW_BUTTON: 'add-crew-buttton',
  CREW_TABLE: 'crew-table',
  COURSE_SELECT: 'course-select',
  MISSION_SELECT: 'mission-select',
  SHOW_TEAM_MATCHER_BUTTON: 'show-team-matcher-button',
  TEAM_MEMBER_COUNT_INPUT: 'team-member-count-input',
  MATCH_TEAM_BUTTON: 'match-team-button',
  TEAM_MATCH_RESULT: 'team-match-result',
  REMATCH_TEAM_BUTTON: 'rematch-team-button',
};
